import '../models/work_order.dart';
import '../models/ppm_plan.dart';
import '../models/asset.dart';

final List<WorkOrderModel> initialWorkOrders = [
  WorkOrderModel(
    id: 'wo-1',
    woNumber: 'WO-2026-000001',
    buildingName: 'Shever Corporate Tower',
    floorLocation: 'Floor 1 - AHU Room 109',
    assetNumber: 'AST-AHU-001',
    assetName: 'Air Handling Unit 01 - North Atrium',
    categoryName: 'HVAC',
    priority: 'High',
    problemDescription:
        'Abnormal grinding noise coming from North Atrium AHU-001 fan section during peak load. Airflow is reduced.',
    status: 'In Progress',
    targetCompletionTime: 'Today, 04:00 PM',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
  ),
  WorkOrderModel(
    id: 'wo-2',
    woNumber: 'WO-2026-000002',
    buildingName: 'Shever Corporate Tower',
    floorLocation: 'Ground Floor - Grand Atrium Lobby',
    categoryName: 'Electrical',
    priority: 'Medium',
    problemDescription:
        '3 ceiling downlights flickering intermittently near the main VIP elevator lobby entrance.',
    status: 'New',
    targetCompletionTime: 'Tomorrow, 10:00 AM',
    createdAt: DateTime.now().subtract(const Duration(minutes: 40)),
  ),
  WorkOrderModel(
    id: 'wo-3',
    woNumber: 'WO-2026-000003',
    buildingName: 'Shever Corporate Tower',
    floorLocation: 'Basement B1 - Pump Room 01',
    assetNumber: 'AST-PMP-001',
    assetName: 'Domestic Potable Water Booster Pump Set',
    categoryName: 'Plumbing',
    priority: 'Emergency',
    problemDescription:
        'High pressure alarm triggered on Potable Water Booster Pump line. Water leakage detected in Basement Pump Room.',
    status: 'Accepted',
    targetCompletionTime: 'Today, 02:00 PM',
    createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
  ),
  WorkOrderModel(
    id: 'wo-4',
    woNumber: 'WO-2026-000004',
    buildingName: 'Shever Corporate Tower',
    floorLocation: 'Floor 1 - Executive Boardroom',
    categoryName: 'Civil',
    priority: 'Low',
    problemDescription: 'Door closer on Executive Boardroom door is slamming shut loudly.',
    status: 'Completed',
    workPerformed: 'Adjusted hydraulic latch speed valves and lubricated hinge bearings.',
    rootCause: 'Valve calibration loosened due to high usage.',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
];

final List<PPMScheduleModel> initialPPMSchedules = [
  PPMScheduleModel(
    id: 'ppm-1',
    scheduleNumber: 'PPM-2026-000101',
    planTitle: 'Monthly Inspection AHU-001',
    assetName: 'AST-AHU-001 (Air Handling Unit)',
    buildingName: 'Shever Corporate Tower',
    frequency: 'Monthly',
    dueDate: '2026-08-29',
    status: 'Scheduled',
    checklist: [
      PPMChecklistItemModel(
        id: 'c-1',
        taskDescription: 'Check and record supply air temperature',
        fieldType: 'numeric_reading',
        unitOfMeasure: '°C',
        minValue: 12.0,
        maxValue: 24.0,
      ),
      PPMChecklistItemModel(
        id: 'c-2',
        taskDescription: 'Inspect air filter condition (Clean/Replace)',
        fieldType: 'pass_fail',
      ),
      PPMChecklistItemModel(
        id: 'c-3',
        taskDescription: 'Check drive belt tension and alignment',
        fieldType: 'pass_fail',
      ),
      PPMChecklistItemModel(
        id: 'c-4',
        taskDescription: 'Measure and record motor operating current',
        fieldType: 'numeric_reading',
        unitOfMeasure: 'Amps',
        minValue: 5.0,
        maxValue: 45.0,
      ),
    ],
  ),
  PPMScheduleModel(
    id: 'ppm-2',
    scheduleNumber: 'PPM-2026-000098',
    planTitle: 'Monthly Health Check Domestic Booster Pumps',
    assetName: 'AST-PMP-001 (Booster Pump Set)',
    buildingName: 'Shever Corporate Tower',
    frequency: 'Monthly',
    dueDate: '2026-08-22',
    status: 'Overdue',
    checklist: [
      PPMChecklistItemModel(
        id: 'c-5',
        taskDescription: 'Check discharge pressure gauge reading',
        fieldType: 'numeric_reading',
        unitOfMeasure: 'Bar',
        minValue: 3.5,
        maxValue: 7.5,
      ),
      PPMChecklistItemModel(
        id: 'c-6',
        taskDescription: 'Inspect mechanical seal for leaks',
        fieldType: 'pass_fail',
      ),
    ],
  ),
];

final List<AssetModel> initialAssets = [
  AssetModel(
    id: 'ast-1',
    assetNumber: 'AST-AHU-001',
    name: 'Air Handling Unit 01 - North Atrium',
    type: 'Air Handling Unit',
    categoryName: 'HVAC',
    manufacturer: 'Carrier',
    model: '39HQ08',
    serialNumber: 'CR-2023-99881',
    buildingName: 'Shever Corporate Tower',
    locationName: 'Floor 1 - AHU Room 109',
    status: 'Active',
    criticality: 'Critical',
  ),
  AssetModel(
    id: 'ast-2',
    assetNumber: 'AST-PMP-001',
    name: 'Domestic Potable Water Booster Pump Set',
    type: 'Booster Pump',
    categoryName: 'Plumbing',
    manufacturer: 'Grundfos',
    model: 'Hydro MPC-E 3',
    serialNumber: 'GF-9908122',
    buildingName: 'Shever Corporate Tower',
    locationName: 'Basement B1 - Pump Room 01',
    status: 'Active',
    criticality: 'High',
  ),
  AssetModel(
    id: 'ast-3',
    assetNumber: 'AST-MDB-001',
    name: 'Main Low Voltage Switchboard MDB-1',
    type: 'Main Distribution Board',
    categoryName: 'Electrical',
    manufacturer: 'Schneider Electric',
    model: 'Prisma Plus P',
    serialNumber: 'SE-2021-0091',
    buildingName: 'Shever Corporate Tower',
    locationName: 'Basement B1 - LV Switchgear',
    status: 'Active',
    criticality: 'Critical',
  ),
];
